---
- name: Install Redis on Ubuntu
  hosts: ubuntu_hosts
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Ensure Redis is running and enabled on boot
      service:
        name: redis-server
        state: started
        enabled: yes
