---
- name: Install Redis on Ubuntu and Debian
  hosts: all
  become: true
  tasks:
    - name: Install Redis
      apt:
        name: redis-server
        state: present
      when: ansible_os_family in ['Debian']

    - name: Ensure Redis is running and enabled
      service:
        name: redis-server
        state: started
        enabled: true
